language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - REPO_NAME=cakephp-uni-login-webservice
    - PLUGIN_NAME=UniLoginWebservice
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2

  matrix:
    - DB=mysql CAKE_VERSION=2.4
    - DB=mysql CAKE_VERSION=2.5
    - DB=mysql CAKE_VERSION=2.6
    - DB=mysql CAKE_VERSION=2.7
    - DB=mysql CAKE_VERSION=2.8

matrix:
  include:
    - php: 5.6
      env:
        - COVERALLS=1
    - php: 5.6
      env:
        - PHPCS=1 PHPCS_ARGS="-p --extensions=php --standard=CakePHP --ignore=vendor/ -n ."
    - php: 5.6
      env:
        - FOC_VALIDATE=1

branches:
  only:
    - master

before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
  hipchat:
    rooms:
      secure: mgmt1F7ywld2/RMf/Id1RwaA8tv9TGRmCpOkkvdQ5stOxBnqY8uA3D10lV6gzEIyfvb0i2EZMOUhF052YO+dJ/+x7bnQOVOsuwumgwPXc5qdXVtYaWp87HUMpM5Zh46L3FbA+LijO01aYQOiX/5OxXWNzxIFL/z1izT7xvA6wKc=
