language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - REPO_NAME=cakephp-uni-login-webservice
    - PLUGIN_NAME=UniLoginWebservice
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2

    - secure: "Xqde++mxhZzCy76OnUZNkwHvBJ9r3LN2w9s+Xb9qrIM3cvOuFp5yGNU+8wSL2zeFf1ix02x+bB6nXRilV06p4JHk1KjZ96RVokaclUh65Y5lVtqhy2JPWnpP9ejFkdxH5aQY9Lt0pQz7v5cV4usnJL4fttE1ZWPoOMttxpL0iRY="

  matrix:
    - CAKE_VERSION=2.9
    - CAKE_VERSION=2.10 PHPUNIT_VERSION=^5.7

matrix:
  include:
    - php: 7.1
      env:
        - CODECOVERAGE=1 PHPUNIT_VERSION=^5.7
    - php: 7.1
      env:
        - PHPCS=1
    - php: 7.1
      env:
        - FOC_VALIDATE=1
  exclude:
    - php: 7.2
      env: CAKE_VERSION=2.9

branches:
  only:
    - master

before_script:
  - git clone -b master https://github.com/Oefenweb/travis --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
  hipchat:
    rooms:
      secure: mgmt1F7ywld2/RMf/Id1RwaA8tv9TGRmCpOkkvdQ5stOxBnqY8uA3D10lV6gzEIyfvb0i2EZMOUhF052YO+dJ/+x7bnQOVOsuwumgwPXc5qdXVtYaWp87HUMpM5Zh46L3FbA+LijO01aYQOiX/5OxXWNzxIFL/z1izT7xvA6wKc=
